


export const PerSplitLeft = {
MidiMode:                                {nrpn:0, range:"0-2", desc:"Split Left MIDI Mode (0: One Channel, 1: Channel Per Note, 2: Channel Per Row)"},
MainChan:                                {nrpn:1, range:"1-16", desc:"Split Left MIDI Main Channel"},
PerNote:                                 {
                                           2: {nrpn: 2, range: "0-1", desc: "Split Left MIDI Per Note Channel 1 (0: Off, 1: On)"},
                                           3: {nrpn: 3, range: "0-1", desc: "Split Left MIDI Per Note Channel 2 (0: Off, 1: On)"},
                                           4: {nrpn: 4, range: "0-1", desc: "Split Left MIDI Per Note Channel 3 (0: Off, 1: On)"},
                                           5: {nrpn: 5, range: "0-1", desc: "Split Left MIDI Per Note Channel 4 (0: Off, 1: On)"},
                                           6: {nrpn: 6, range: "0-1", desc: "Split Left MIDI Per Note Channel 5 (0: Off, 1: On)"},
                                           7: {nrpn: 7, range: "0-1", desc: "Split Left MIDI Per Note Channel 6 (0: Off, 1: On)"},
                                           8: {nrpn: 8, range: "0-1", desc: "Split Left MIDI Per Note Channel 7 (0: Off, 1: On)"},
                                           9: {nrpn: 9, range: "0-1", desc: "Split Left MIDI Per Note Channel 8 (0: Off, 1: On)"},
                                           10: {nrpn: 10, range: "0-1", desc: "Split Left MIDI Per Note Channel 9 (0: Off, 1: On)"},
                                           11: {nrpn: 11, range: "0-1", desc: "Split Left MIDI Per Note Channel 10 (0: Off, 1: On)"},
                                           12: {nrpn: 12, range: "0-1", desc: "Split Left MIDI Per Note Channel 11 (0: Off, 1: On)"},
                                           13: {nrpn: 13, range: "0-1", desc: "Split Left MIDI Per Note Channel 12 (0: Off, 1: On)"},
                                           14: {nrpn: 14, range: "0-1", desc: "Split Left MIDI Per Note Channel 13 (0: Off, 1: On)"},
                                           15: {nrpn: 15, range: "0-1", desc: "Split Left MIDI Per Note Channel 14 (0: Off, 1: On)"},
                                           16: {nrpn: 16, range: "0-1", desc: "Split Left MIDI Per Note Channel 15 (0: Off, 1: On)"},
                                           17: {nrpn: 17, range: "0-1", desc: "Split Left MIDI Per Note Channel 16 (0: Off, 1: On)"},
                                         },
PerRowLowestChannel:                    {nrpn:18, range:"1-16", desc:"Split Left MIDI Per Row Lowest Channel"},
BendRange:                              {nrpn:19, range:"1-96", desc:"Split Left MIDI Bend Range"},
SendX:                                  {nrpn:20, range:"0-1", desc:"Split Left Send X (0: Off, 1: On)"},
Quantize:                               {nrpn:21, range:"0-1", desc:"Split Left Pitch Quantize (0: Off, 1: On)"},
QuantizeHold:                           {nrpn:22, range:"0-3", desc:"Split Left Pitch Quantize Hold (0: Off, 1: Medium, 2: Fast, 3: Slow)"},
PitchResetOnRelease:                    {nrpn:23, range:"0-1", desc:"Split Left Pitch Reset On Release (unprinted parameter, 0: Off, 1: On)"},
SendY:                                  {nrpn:24, range:"0-1", desc:"Split Left Send Y (0: Off, 1: On)"},
CCforY:                                 {nrpn:25, range:"0-127", desc:"Split Left MIDI CC For Y (CC 1 or CC 74 are recommended, any CC is possible though)"},
RelativeY:                              {nrpn:26, range:"0-1", desc:"Split Left Relative Y (0: Off, 1: On)"},
SendZ:                                  {nrpn:27, range:"0-1", desc:"Split Left Send Z (0: Off, 1: On)"},
ExpressionForZ:                         {nrpn:28, range:"0-2", desc:"Split Left MIDI Expression For Z (0: Poly Aftertouch, 1: Channel Aftertouch, 2: CC defined in #29)"},
CCforZ:                                 {nrpn:29, range:"0-127", desc:"Split Left MIDI CC For Z (CC 11 is recommended, any CC is possible though)"},
ColorMain:                              {nrpn:30, range:"1-6", desc:"Split Left Color Main (see color value table below)"},
ColorAccent:                            {nrpn:31, range:"1-6", desc:"Split Left Color Accent (see color value table below)"},
ColorPlayed:                            {nrpn:32, range:"0-6", desc:"Split Left Color Played (see color value table below)"},
ColorLowRow:                            {nrpn:33, range:"1-6", desc:"Split Left Color LowRow (see color value table below)"},
LowRowMode:                             {nrpn:34, range:"0-7", desc:"Split Left LowRow Mode (0: Off, 1: Sust, 2: Restr, 3: Strum, 4: Arp, 5: Bend, 6: CC1, 7: CC16-18)"},
Special:                                {nrpn:35, range:"0-3", desc:"Split Left Special (0: Off, 1: Arpeg, 2: CC Faders, 3: Strum, 4: Sequencer)"},
Octave:                                 {nrpn:36, range:"0-10", desc:"Split Left Octave (0: —5, 1: -4, 2: -3, 3: -2, 4: -1, 5: 0, 6: +1, 7: +2, 8: +3, 9: +4. 10: +5)"},
TransPitch:                             {nrpn:37, range:"0-14", desc:"Split Left Transpose Pitch (0-6: -7 to -1, 7: 0, 8-14: +1 to +7)"},
TransLightsAndPitch:                    {nrpn:38, range:"0-14", desc:"Split Left Transpose Lights (0-6: -7 to -1, 7: 0, 8-14: +1 to +7)"},
ExpressionForY:                         {nrpn:39, range:"0-2", desc:"Split Left MIDI Expression For Y (0: Poly Aftertouch, 1: Channel Aftertouch, 2: CC defined in #25)"},
CCforFader1:                            {nrpn:40, range:"0-128", desc:"Split Left MIDI CC For Fader 1 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader2:                            {nrpn:41, range:"0-128", desc:"Split Left MIDI CC For Fader 2 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader3:                            {nrpn:42, range:"0-128", desc:"Split Left MIDI CC For Fader 3 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader4:                            {nrpn:43, range:"0-128", desc:"Split Left MIDI CC For Fader 4 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader5:                            {nrpn:44, range:"0-128", desc:"Split Left MIDI CC For Fader 5 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader6:                            {nrpn:45, range:"0-128", desc:"Split Left MIDI CC For Fader 6 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader7:                            {nrpn:46, range:"0-128", desc:"Split Left MIDI CC For Fader 7 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader8:                            {nrpn:47, range:"0-128", desc:"Split Left MIDI CC For Fader 8 (0-127: CC, 128: Channel Aftertouch)"},
LowRowXBehavior:                        {nrpn:48, range:"0-1", desc:"Split Left LowRow X Behavior (0: Hold, 1: Fader)"},
CCforLowRow:                            {nrpn:49, range:"0-128", desc:"Split Left MIDI CC For LowRow X (0-127: CC, 128: Channel Aftertouch)"},
LowRowXYZBehavior:                      {nrpn:50, range:"0-1", desc:"Split Left LowRow XYZ Behavior (0: Hold, 1: Fader)"},
CCforLowRowXyzX:                        {nrpn:51, range:"0-128", desc:"Split Left MIDI CC For LowRow XYZ X (0-127: CC, 128: Channel Aftertouch)"},
CCforLowRowXyzY:                        {nrpn:52, range:"0-128", desc:"Split Left MIDI CC For LowRow XYZ Y (0-127: CC, 128: Channel Aftertouch)"},
CCforLowRowXyzZ:                        {nrpn:53, range:"0-128", desc:"Split Left MIDI CC For LowRow XYZ Z (0-127: CC, 128: Channel Aftertouch)"},
CCYmin:                                 {nrpn:54, range:"0-127", desc:"Split Left Minimum CC Value For Y"},
CCYmax:                                 {nrpn:55, range:"0-127", desc:"Split Left Maximum CC Value For Y"},
CCZmin:                                 {nrpn:56, range:"0-127", desc:"Split Left Minimum CC Value For Z"},
CCZmax:                                 {nrpn:57, range:"0-127", desc:"Split Left Maximum CC Value For Z"},
CCforZ14bit:                            {nrpn:58, range:"0-1", desc:"Split Left CC Value For Z in 14-bit"},
InitValRelativeY:                       {nrpn:59, range:"0-127", desc:"Split Left Initial Value For Relative Y"},
ChannelPerRowChannelOrder:              {nrpn:60, range:"0-1", desc:"Split Left Channel Per Row MIDI Channel Order (0: Normal, 1: Reversed)"},
TouchAnimation:                         {nrpn:61, range:"0-11", desc:"Split Left Touch Animation (0: Same, 1: Crosses, 2: Circles, 3: Squares, 4: Diamonds, 5: Stars, 6: Sparkles, 7: Curtains, 8: Blinds, 9: Targets, 10: Up, 11: Down, 12: Left, 13: Right, 14: Orbits)"},
SeqTogglePlay:                          {nrpn:62, range:"1", desc:"Split Left Sequencer Toggle Play"},
SeqPrevPattern:                         {nrpn:63, range:"1", desc:"Split Left Sequencer Previous Pattern"},
SeqNextPatter:                          {nrpn:64, range:"1", desc:"Split Left Sequencer Next Pattern"},
SeqSelectPattern:                       {nrpn:65, range:"0-3", desc:"Split Left Sequencer Select Pattern Number"},
SeqToggleMute:                          {nrpn:66, range:"1", desc:"Split Left Sequencer Toggle Mute"},
           };

const PerRightSplit = {
MidiMode:                               {nrpn:100, range:"0-2", desc:"Split Right MIDI Mode (0: One Channel, 1: Channel Per Note, 2: Channel Per Row)"},
MainChan:                               {nrpn:101, range:"1-16", desc:"Split Right MIDI Main Channel"},
PerNote: {
  102: {nrpn: 102, range: "0-1", desc: "Split Right MIDI Per Note Channel 1 (0: Off, 1: On)"},
  103: {nrpn: 103, range: "0-1", desc: "Split Right MIDI Per Note Channel 2 (0: Off, 1: On)"},
  104: {nrpn: 104, range: "0-1", desc: "Split Right MIDI Per Note Channel 3 (0: Off, 1: On)"},
  105: {nrpn: 105, range: "0-1", desc: "Split Right MIDI Per Note Channel 4 (0: Off, 1: On)"},
  106: {nrpn: 106, range: "0-1", desc: "Split Right MIDI Per Note Channel 5 (0: Off, 1: On)"},
  107: {nrpn: 107, range: "0-1", desc: "Split Right MIDI Per Note Channel 6 (0: Off, 1: On)"},
  108: {nrpn: 108, range: "0-1", desc: "Split Right MIDI Per Note Channel 7 (0: Off, 1: On)"},
  109: {nrpn: 109, range: "0-1", desc: "Split Right MIDI Per Note Channel 8 (0: Off, 1: On)"},
  110: {nrpn: 110, range: "0-1", desc: "Split Right MIDI Per Note Channel 9 (0: Off, 1: On)"},
  111: {nrpn: 111, range: "0-1", desc: "Split Right MIDI Per Note Channel 10 (0: Off, 1: On)"},
  112: {nrpn: 112, range: "0-1", desc: "Split Right MIDI Per Note Channel 11 (0: Off, 1: On)"},
  113: {nrpn: 113, range: "0-1", desc: "Split Right MIDI Per Note Channel 12 (0: Off, 1: On)"},
  114: {nrpn: 114, range: "0-1", desc: "Split Right MIDI Per Note Channel 13 (0: Off, 1: On)"},
  115: {nrpn: 115, range: "0-1", desc: "Split Right MIDI Per Note Channel 14 (0: Off, 1: On)"},
  116: {nrpn: 116, range: "0-1", desc: "Split Right MIDI Per Note Channel 15 (0: Off, 1: On)"},
  117: {nrpn: 117, range: "0-1", desc: "Split Right MIDI Per Note Channel 16 (0: Off, 1: On)"},
},
PerRowLowestChannel:                      {nrpn:118, range:"1-16", desc:"Split Right MIDI Per Row Lowest Channel"},
BendRange:                                {nrpn:119, range:"1-96", desc:"Split Right MIDI Bend Range"},
SendX:                          {nrpn:120, range:"0-1", desc:"Split Right Send X (0: Off, 1: On)"},
Quantize:                       {nrpn:121, range:"0-1", desc:"Split Right Pitch Quantize (0: Off, 1: On)"},
QuantizeHold:                   {nrpn:122, range:"0-1", desc:"Split Right Pitch Quantize Hold (0: Off, 1: Medium, 2: Fast, 3: Slow)"},
PitchResetOnRelease:            {nrpn:123, range:"0-1", desc:"Split Right Pitch Reset On Release (unprinted parameter, 0: Off, 1: On)"},
SendY:                          {nrpn:124, range:"0-1", desc:"Split Right Send Y (0: Off, 1: On)"},
CCforY:                         {nrpn:125, range:"0-127", desc:"Split Right MIDI CC For Y (CC 1 or CC 74 are recommended, any CC is possible though)"},
RelativeY:                      {nrpn:126, range:"0-1", desc:"Split Right Relative Y (0: Off, 1: On)"},
SendZ:                          {nrpn:127, range:"0-1", desc:"Split Right Send Z (0: Off, 1: On)"},
ExpressionForZ:                 {nrpn:128, range:"0-2", desc:"Split Right MIDI Expression For Z (0: Poly Aftertouch, 1: Channel Aftertouch, 2: CC defined in #129)"},
CCforZ:                         {nrpn:129, range:"0-127", desc:"Split Right MIDI CC For Z (CC 11 is recommended, any CC is possible though)"},
ColorMain:                      {nrpn:130, range:"1-6", desc:"Split Right Color Main (see color value table below)"},
ColorAccent:                    {nrpn:131, range:"1-6", desc:"Split Right Color Accent (see color value table below)"},
ColorPlayed:                    {nrpn:132, range:"0-6", desc:"Split Right Color Played (see color value table below)"},
ColorLowRow:                    {nrpn:133, range:"1-6", desc:"Split Right Color LowRow (see color value table below)"},
LowRowMode:                     {nrpn:134, range:"0-7", desc:"Split Right LowRow Mode (0: Off, 1: Sust, 2: Restr, 3: Strum, 4: Arp, 5: Bend, 6: CC1, 7: CC16-18)"},
Special:                        {nrpn:135, range:"0-1", desc:"Split Right Special (0: Off, 1: Arpeg, 2: CC Faders, 3: Strum, 4: Sequencer"},
Octave:                         {nrpn:136, range:"0-10", desc:"Split Right Octave (0: —5, 1: -4, 2: -3, 3: -2, 4: -1, 5: 0, 6: +1, 7: +2, 8: +3, 9: +4. 10: +5)"},
TransPitch:                     {nrpn:137, range:"0-14", desc:"Split Right Transpose Pitch (0-6: -7 to -1, 7: 0, 8-14: +1 to +7)"},
TransLightsAndPitch:            {nrpn:138, range:"0-14", desc:"Split Right Transpose Lights (0-6: -7 to -1, 7: 0, 8-14: +1 to +7)"},
ExpressionForY:                 {nrpn:139, range:"0-2", desc:"Split Right MIDI Expression For Y (0: Poly Aftertouch, 1: Channel Aftertouch, 2: CC defined in #125)"},
CCforFader1:                    {nrpn:140, range:"0-128", desc:"Split Right MIDI CC For Fader 1 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader2:                    {nrpn:141, range:"0-128", desc:"Split Right MIDI CC For Fader 2 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader3:                    {nrpn:142, range:"0-128", desc:"Split Right MIDI CC For Fader 3 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader4:                    {nrpn:143, range:"0-128", desc:"Split Right MIDI CC For Fader 4 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader5:                    {nrpn:144, range:"0-128", desc:"Split Right MIDI CC For Fader 5 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader6:                    {nrpn:145, range:"0-128", desc:"Split Right MIDI CC For Fader 6 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader7:                    {nrpn:146, range:"0-128", desc:"Split Right MIDI CC For Fader 7 (0-127: CC, 128: Channel Aftertouch)"},
CCforFader8:                    {nrpn:147, range:"0-128", desc:"Split Right MIDI CC For Fader 8 (0-127: CC, 128: Channel Aftertouch)"},
LowRowXBehavior:                {nrpn:148, range:"0-1", desc:"Split Right LowRow X Behavior (0: Hold, 1: Fader)"},
CCforLowRow:                    {nrpn:149, range:"0-128", desc:"Split Right MIDI CC For LowRow X (0-127: CC, 128: Channel Aftertouch)"},
LowRowXYZBehavior:              {nrpn:150, range:"0-1", desc:"Split Right LowRow XYZ Behavior (0: Hold, 1: Fader)"},
CCforLowRowXyzX:                {nrpn:151, range:"0-128", desc:"Split Right MIDI CC For LowRow XYZ X (0-127: CC, 128: Channel Aftertouch)"},
CCforLowRowXyzY:                {nrpn:152, range:"0-128", desc:"Split Right MIDI CC For LowRow XYZ Y (0-127: CC, 128: Channel Aftertouch)"},
CCforLowRowXyzZ:                {nrpn:153, range:"0-128", desc:"Split Right MIDI CC For LowRow XYZ Z (0-127: CC, 128: Channel Aftertouch)"},
CCYmin:                         {nrpn:154, range:"0-127", desc:"Split Right Minimum CC Value For Y"},
CCYmax:                         {nrpn:155, range:"0-127", desc:"Split Right Maximum CC Value For Y"},
CCZmin:                         {nrpn:156, range:"0-127", desc:"Split Right Minimum CC Value For Z"},
CCZmax:                         {nrpn:157, range:"0-127", desc:"Split Right Maximum CC Value For Z"},
CCforZ14bit:                    {nrpn:158, range:"0-1", desc:"Split Right CC Value For Z in 14-bit"},
InitValRelativeY:               {nrpn:159, range:"0-127", desc:"Split Right Initial Value For Relative Y"},
ChannelPerRowChannelOrder:      {nrpn:160, range:"0-1", desc:"Split Right Channel Per Row MIDI Channel Order (0: Normal, 1: Reversed)"},
TouchAnimation:                 {nrpn:161, range:"0-11", desc:"Split Right Touch Animation (0: Same, 1: Crosses, 2: Circles, 3: Squares, 4: Diamonds, 5: Stars, 6: Sparkles, 7: Curtains, 8: Blinds, 9: Targets, 10: Up, 11: Down, 12: Left, 13: Right, 14: Orbits)"},
SeqTogglePlay:                  {nrpn:162, range:"1", desc:"Split Right Sequencer Toggle Play"},
SeqPrevPattern:                 {nrpn:163, range:"1", desc:"Split Right Sequencer Previous Pattern"},
SeqNextPatter:                  {nrpn:164, range:"1", desc:"Split Right Sequencer Next Pattern"},
SeqSelectPattern:               {nrpn:165, range:"0-3", desc:"Split Right Sequencer Select Pattern Number"},
SeqToggleMute:                  {nrpn:166, range:"1", desc:"Split Right Sequencer Toggle Mute"},
     }     ;


const Global = {
SplitActive:                            {nrpn:200, range:"0-1", desc:"Global Split Active (0: Inactive, 1: Active)"},
SplitSelected:                            {nrpn:201, range:"0-1", desc:"Global Selected Split (0: Left Split, 1: Right Split)"},
SplitPointColumn:                            {nrpn:202, range:"2-25", desc:"Global Split Point Column"},
NoteLightsMain: [
  {nrpn:203, range:"0-1", desc:"Global Main Note Light C (0: Off, 1: On)"},
  {nrpn:204, range:"0-1", desc:"Global Main Note Light C# (0: Off, 1: On)"},
  {nrpn:205, range:"0-1", desc:"Global Main Note Light D (0: Off, 1: On)"},
  {nrpn:206, range:"0-1", desc:"Global Main Note Light D# (0: Off, 1: On)"},
  {nrpn:207, range:"0-1", desc:"Global Main Note Light E (0: Off, 1: On)"},
  {nrpn:208, range:"0-1", desc:"Global Main Note Light F (0: Off, 1: On)"},
  {nrpn:209, range:"0-1", desc:"Global Main Note Light F# (0: Off, 1: On)"},
  {nrpn:210, range:"0-1", desc:"Global Main Note Light G (0: Off, 1: On)"},
  {nrpn:211, range:"0-1", desc:"Global Main Note Light G# (0: Off, 1: On)"},
  {nrpn:212, range:"0-1", desc:"Global Main Note Light A (0: Off, 1: On)"},
  {nrpn:213, range:"0-1", desc:"Global Main Note Light A# (0: Off, 1: On)"},
  {nrpn:214, range:"0-1", desc:"Global Main Note Light B (0: Off, 1: On)"},
],
NoteLightsAccent: [
 {nrpn:215, range:"0-1", desc:"Global Accent Note Light C (0: Off, 1: On)"},
 {nrpn:216, range:"0-1", desc:"Global Accent Note Light C# (0: Off, 1: On)"},
 {nrpn:217, range:"0-1", desc:"Global Accent Note Light D (0: Off, 1: On)"},
 {nrpn:218, range:"0-1", desc:"Global Accent Note Light D# (0: Off, 1: On)"},
 {nrpn:219, range:"0-1", desc:"Global Accent Note Light E (0: Off, 1: On)"},
 {nrpn:220, range:"0-1", desc:"Global Accent Note Light F (0: Off, 1: On)"},
 {nrpn:221, range:"0-1", desc:"Global Accent Note Light F# (0: Off, 1: On)"},
 {nrpn:222, range:"0-1", desc:"Global Accent Note Light G (0: Off, 1: On)"},
 {nrpn:223, range:"0-1", desc:"Global Accent Note Light G# (0: Off, 1: On)"},
 {nrpn:224, range:"0-1", desc:"Global Accent Note Light A (0: Off, 1: On)"},
 {nrpn:225, range:"0-1", desc:"Global Accent Note Light A# (0: Off, 1: On)"},
 {nrpn:226, range:"0-1", desc:"Global Accent Note Light B (0: Off, 1: On)"},
],
RowOffset:                      {nrpn:227, range:"0-13", desc:"Global Row Offset (only supports, 0: No overlap, 3 4 5 6 7 12: Intervals, 13: Guitar, 127: 0 offset)"},
Switch1Assignment:              {nrpn:228, range:"0-5", desc:"Global Switch 1 Assignment (0: Oct Down, 1: Oct Up, 2: Sustain, 3: CC65, 4: Arp, 5: Alt Split, 6: Auto Octave, 7: Tap Tempo, 8: Legato, 9: Latch, 10: Preset Up, 11: Preset Down, 12: Reverse Pitch X, 13: Sequencer Play, 14: Sequencer Previous, 15: Sequencer Next, 16: Send MIDI Clock, 17: Sequencer Mute)"},
Switch2Assignment:              {nrpn:229, range:"0-5", desc:"Global Switch 2 Assignment (0: Oct Down, 1: Oct Up, 2: Sustain, 3: CC65, 4: Arp, 5: Alt Split, 6: Auto Octave, 7: Tap Tempo, 8: Legato, 9: Latch, 10: Preset Up, 11: Preset Down, 12: Reverse Pitch X, 13: Sequencer Play, 14: Sequencer Previous, 15: Sequencer Next, 16: Send MIDI Clock, 17: Sequencer Mute)"},
FootLeftAssignment:             {nrpn:230, range:"0-5", desc:"Global Foot Left Assignment (0: Oct Down, 1: Oct Up, 2: Sustain, 3: CC65, 4: Arp, 5: Alt Split, 6: Auto Octave, 7: Tap Tempo, 8: Legato, 9: Latch, 10: Preset Up, 11: Preset Down, 12: Reverse Pitch X, 13: Sequencer Play, 14: Sequencer Previous, 15: Sequencer Next, 16: Send MIDI Clock, 17: Sequencer Mute)"},
FootRightAssignment:            {nrpn:231, range:"0-5", desc:"Global Foot Right Assignment (0: Oct Down, 1: Oct Up, 2: Sustain, 3: CC65, 4: Arp, 5: Alt Split, 6: Auto Octave, 7: Tap Tempo, 8: Legato, 9: Latch, 10: Preset Up, 11: Preset Down, 12: Reverse Pitch X, 13: Sequencer Play, 14: Sequencer Previous, 15: Sequencer Next, 16: Send MIDI Clock, 17: Sequencer Mute)"},
SensitivityVelocity:            {nrpn:232, range:"0-3", desc:"Global Velocity Sensitivity (0: Low, 1: Medium, 2: High, 3: Fixed)"},
SensitivityPressure:            {nrpn:233, range:"0-2", desc:"Global Pressure Sensitivity (0: Low, 1: Medium, 2: High)"},
DeviceIO:                       {nrpn:234, range:"0-1", desc:"Device MIDI I/O (0: MIDI Jacks, 1: USB)"},
ArpDirection:                   {nrpn:235, range:"0-4", desc:"Global Arp Direction (0: Up, 1: Down, 2: Up Down, 3: Random, 4: Replay All)"},
ArpTempoNoteValue:              {nrpn:236, range:"1-7", desc:"Global Arp Tempo Note Value (1: 8, 2: 8 Tri, 3: 16, 4: 16 Swing, 5: 16 Tri, 6: 32, 7: 32 Tri)"},
ArpOctaveExtension:             {nrpn:237, range:"0-2", desc:"Global Arp Octave Extension (0: None, 1: +1, 2: +2)"},
ClockBeatsPerMin:               {nrpn:238, range:"1-360", desc:"Global Clock BPM (applies when receiving no MIDI clock)"},
Switch1BothSplits:              {nrpn:239, range:"0-1", desc:"Global Switch 1 Both Splits (0: Off, 1: On)"},
Switch2BothSplits:              {nrpn:240, range:"0-1", desc:"Global Switch 2 Both Splits (0: Off, 1: On)"},
FootLeftBothSplits:             {nrpn:241, range:"0-1", desc:"Global Foot Left Both Splits (0: Off, 1: On)"},
FootRightBothSplits:            {nrpn:242, range:"0-1", desc:"Global Foot Right Both Splits (0: Off, 1: On)"},
LoadPreset:                     {nrpn:243, range:"0-5", desc:"Global Settings Preset Load"},
PressureAftertouch:             {nrpn:244, range:"0-1", desc:"Global Pressure Aftertouch (0: Off, 1: On)"},
DeviceUserFirmwareMode:               {nrpn:245, range:"0-1", desc:"Device User Firmware Mode (0: Off, 1: On)"},
DeviceLeftHandedOperation:      {nrpn:246, range:"0-1", desc:"Device Left Handed Operation (0: Off, 1: On)"},
247:                            {nrpn:247, range:"0-11", desc:"Global Active Note Lights Preset"},
248:                            {nrpn:248, range:"0-127", desc:"Global MIDI CC For Switch CC65 (Changes the CC for all switches - Legacy option, see NRPN 255-258)"},
249:                            {nrpn:249, range:"1-127", desc:"Global Minimum Value For Velocity"},
250:                            {nrpn:250, range:"1-127", desc:"Global Maximum Value For Velocity"},
251:                            {nrpn:251, range:"1-127", desc:"Global Value For Fixed Velocity"},
252:                            {nrpn:252, range:"0-512", desc:"Device Minimum Interval Between MIDI Bytes Over USB"},
253:                            {nrpn:253, range:"0-33", desc:"Global Custom Row Offset Instead Of Octave (0-32: -16-16 semitone intervals, 33: inverted Guitar)"},
254:                            {nrpn:254, range:"0-1", desc:"Device MIDI Through (0: Off, 1: On)"},
255:                            {nrpn:255, range:"0-127", desc:"Global MIDI CC For Foot Left CC65"},
256:                            {nrpn:256, range:"0-127", desc:"Global MIDI CC For Foot Right CC65"},
257:                            {nrpn:257, range:"0-127", desc:"Global MIDI CC For Switch 1 CC65"},
258:                            {nrpn:258, range:"0-127", desc:"Global MIDI CC For Switch 2 CC65"},
259:                            {nrpn:259, range:"0-127", desc:"Global MIDI CC For Foot Left Sustain"},
260:                            {nrpn:260, range:"0-127", desc:"Global MIDI CC For Foot Right Sustain"},
261:                            {nrpn:261, range:"0-127", desc:"Global MIDI CC For Switch 1 Sustain"},
262:                            {nrpn:262, range:"0-127", desc:"Global MIDI CC For Switch 2 Sustain"},
GuitarTuningPerRow: [
 {nrpn:263, range:"0-127", desc:"Global Note Number For Guitar Tuning Row 1"},
 {nrpn:264, range:"0-127", desc:"Global Note Number For Guitar Tuning Row 2"},
 {nrpn:265, range:"0-127", desc:"Global Note Number For Guitar Tuning Row 3"},
 {nrpn:266, range:"0-127", desc:"Global Note Number For Guitar Tuning Row 4"},
 {nrpn:267, range:"0-127", desc:"Global Note Number For Guitar Tuning Row 5"},
 {nrpn:268, range:"0-127", desc:"Global Note Number For Guitar Tuning Row 6"},
 {nrpn:269, range:"0-127", desc:"Global Note Number For Guitar Tuning Row 7"},
 {nrpn:270, range:"0-127", desc:"Global Note Number For Guitar Tuning Row 8"},
]
};
